# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Polylint < Formula
  desc "Polylint: Extensible generic linter"
  homepage "https://github.com/zph/polylint"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zph/polylint/releases/download/v0.0.3/polylint_darwin_x86_64.tar.gz"
      sha256 "875da672de60ddf67e7d94f743e38aeb6d12c6bb9cd639a0556c1cb7ec5b5c72"

      def install
        bin.install "polylint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zph/polylint/releases/download/v0.0.3/polylint_darwin_arm64.tar.gz"
      sha256 "836ecad62c0578c9ece92628cb86afa141aad09bc61269ce0b630a92d75b167d"

      def install
        bin.install "polylint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zph/polylint/releases/download/v0.0.3/polylint_linux_x86_64.tar.gz"
      sha256 "c43386d61898f9bc04051ef55c0977d22dfecf8a1176930c314ff374efe2b255"

      def install
        bin.install "polylint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zph/polylint/releases/download/v0.0.3/polylint_linux_arm64.tar.gz"
      sha256 "32aad77d883b9f6acc8d37098679a0f890e4150bcfd42c34be86ecc9887d03ce"

      def install
        bin.install "polylint"
      end
    end
  end

  head "https://github.com/zph/polylint.git"

  test do
    system "#{bin}/polylint --version"
  end
end
