# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Polylint < Formula
  desc "Polylint: Extensible generic linter"
  homepage "https://github.com/zph/polylint"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zph/polylint/releases/download/v0.0.1/polylint_Darwin_x86_64.tar.gz"
      sha256 "258aae10c3667e947882ba58f0577d00f3cbcf071b80cc234a12c6d176db790b"

      def install
        bin.install "polylint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zph/polylint/releases/download/v0.0.1/polylint_Darwin_arm64.tar.gz"
      sha256 "16523d06970e2877a6a78104bf08d92ef71214d29e42accd438f96173dcc7e83"

      def install
        bin.install "polylint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zph/polylint/releases/download/v0.0.1/polylint_Linux_x86_64.tar.gz"
      sha256 "a27ed72eef00d89e8dbb71930b20f333b4d40e66006952e649fdb65a9a61e422"

      def install
        bin.install "polylint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zph/polylint/releases/download/v0.0.1/polylint_Linux_arm64.tar.gz"
      sha256 "34bd974561ddd5ef462872454198a6103957373da72d5c7d03efad13abddcc9d"

      def install
        bin.install "polylint"
      end
    end
  end

  head "https://github.com/zph/polylint.git"

  test do
    system "#{bin}/polylint --version"
  end
end
