# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Polylint < Formula
  desc "Polylint: Extensible generic linter"
  homepage "https://github.com/zph/polylint"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zph/polylint/releases/download/v0.0.5/polylint_darwin_x86_64.tar.gz"
      sha256 "80f1447fbcee99c9cee2789c5fe3048379ba60f3dc481516ced70e78016f34a2"

      def install
        bin.install "polylint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zph/polylint/releases/download/v0.0.5/polylint_darwin_arm64.tar.gz"
      sha256 "d7221479c7d0635c9d9960584bb3d68203c3d813094510a2586cb509d6da39ca"

      def install
        bin.install "polylint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zph/polylint/releases/download/v0.0.5/polylint_linux_x86_64.tar.gz"
      sha256 "814fb8775b3ac202ba5f0e67d88c98ca021c98dbed57977ffcfe35c88cb73ee8"

      def install
        bin.install "polylint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zph/polylint/releases/download/v0.0.5/polylint_linux_arm64.tar.gz"
      sha256 "b40274c0fa63aabd0e3a9461a2bd3c2db13acb7b2533be49e7dfc2b4b3dd5263"

      def install
        bin.install "polylint"
      end
    end
  end

  head "https://github.com/zph/polylint.git"

  test do
    system "#{bin}/polylint --version"
  end
end
